import mongoose from "mongoose";

/**
 * URL Schema
 * Stores shortened URLs with visit history and owner reference.
 */
const urlSchema = new mongoose.Schema(
  {
    // Unique 8-character alphanumeric short ID (generated by nanoid)
    shortId: {
      type: String,
      required: true,
      unique: true,
    },

    // The original long URL that this short ID redirects to
    redirectUrl: {
      type: String,
      required: true,
    },
    // Array of visit timestamps — each entry represents one click
    visitedHistory: [
      {
        _id: false,
        timestamp: {
          type: Date,
        },
      },
    ],
    // Reference to the user who created this short URL
    createdBy: {
      type: mongoose.Types.ObjectId,
      ref: "users",
    },
  },
  { timestamps: true },
);

const URL = mongoose.model("url", urlSchema);

export default URL;
